import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ExternalLink, FileCode2, Layers3, Minus, Plus, RotateCcw, Route, Search } from 'lucide-react';
import { api, getApiError } from '../api/client';

export interface ArchitectureNode { id: string; label: string; kind: 'Module'|'File'|'Endpoint'; path?: string; language?: string; childCount: number; sourceUrl?: string }
export interface ArchitectureEdge { id: string; sourceId: string; targetId: string; kind: string; label: string }
export interface ArchitectureGraph { schemaVersion: string; commitSha: string; isTruncated: boolean; totalNodeCount: number; nodes: ArchitectureNode[]; edges: ArchitectureEdge[] }

const icons = { Module: Layers3, File: FileCode2, Endpoint: Route };
export function filterArchitectureNodes(nodes: ArchitectureNode[], kind: string, search: string) {
  const term = search.trim().toLowerCase();
  return nodes.filter(node => (kind === 'All' || node.kind === kind) && (!term || `${node.label} ${node.path ?? ''} ${node.language ?? ''}`.toLowerCase().includes(term)));
}

export function RepositoryArchitectureMap({ organizationId, repositoryId }: { organizationId: string; repositoryId: string }) {
  const graph = useQuery({ queryKey: ['repository-architecture', organizationId, repositoryId], queryFn: async () => (await api.get<ArchitectureGraph>(`/organizations/${organizationId}/repositories/${repositoryId}/architecture`)).data });
  const [search, setSearch] = useState(''); const [kind, setKind] = useState('All'); const [selectedId, setSelectedId] = useState<string>(); const [zoom, setZoom] = useState(1);
  const filtered = useMemo(() => filterArchitectureNodes(graph.data?.nodes ?? [], kind, search), [graph.data, kind, search]);
  if (graph.isLoading) return <p role="status" className="text-sm text-slate-500">Building the repository architecture map...</p>;
  if (graph.isError) return <div role="alert" className="error">Architecture map unavailable. {getApiError(graph.error)}</div>;
  if (!graph.data?.nodes.length) return <div className="rounded-xl border border-slate-200 p-6 text-center"><h3 className="font-semibold text-ink">No architecture data yet</h3><p className="mt-2 text-sm text-slate-500">Re-index this repository after adding supported source files.</p></div>;
  const selected = graph.data.nodes.find(node => node.id === selectedId) ?? filtered[0];
  const relationships = selected ? graph.data.edges.filter(edge => edge.sourceId === selected.id || edge.targetId === selected.id) : [];
  const zoomButton = 'rounded-lg border border-slate-200 p-2 text-slate-600 transition hover:border-brand-300 hover:text-brand-600 focus:outline-none focus:ring-2 focus:ring-brand-500';
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-slate-500">Commit-pinned map for {graph.data.commitSha.slice(0, 8)}. Select a component for its location and relationships.</p>{graph.data.isTruncated && <p className="mt-1 text-xs font-semibold text-amber-700">Showing a representative {graph.data.nodes.length} of {graph.data.totalNodeCount} nodes.</p>}</div><div className="flex gap-1" aria-label="Map zoom controls"><button className={zoomButton} aria-label="Zoom out" onClick={() => setZoom(value => Math.max(.7, value - .1))}><Minus size={15}/></button><button className={zoomButton} aria-label="Reset zoom" onClick={() => setZoom(1)}><RotateCcw size={15}/></button><button className={zoomButton} aria-label="Zoom in" onClick={() => setZoom(value => Math.min(1.4, value + .1))}><Plus size={15}/></button></div></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-[minmax(0,1fr)_12rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 text-slate-400" size={16}/><span className="sr-only">Search architecture nodes</span><input className="control pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search components or files"/></label><select className="control" aria-label="Component type" value={kind} onChange={event => setKind(event.target.value)}><option>All</option><option>Module</option><option>File</option><option>Endpoint</option></select></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="max-h-[42rem] overflow-auto rounded-xl border border-slate-200 bg-slate-50 p-4" aria-label={`Architecture map with ${filtered.length} visible nodes`}><div className="grid min-w-[34rem] gap-5 transition-transform motion-reduce:transition-none" style={{ transform: `scale(${zoom})`, transformOrigin: 'top left' }}>{['Module','File','Endpoint'].map(group => { const nodes = filtered.filter(node => node.kind === group); if (!nodes.length) return null; return <section key={group} aria-labelledby={`architecture-${group}`}><h3 id={`architecture-${group}`} className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{group}s</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{nodes.map(node => { const Icon = icons[node.kind]; return <button key={node.id} type="button" aria-pressed={selected?.id === node.id} onClick={() => setSelectedId(node.id)} className={`rounded-xl border bg-white p-3 text-left transition focus:outline-none focus:ring-2 focus:ring-brand-500 ${selected?.id === node.id ? 'border-brand-500' : 'border-slate-200 hover:border-brand-300'}`}><span className="flex items-center gap-2"><Icon size={16} className="shrink-0 text-brand-600"/><span className="min-w-0 truncate text-sm font-semibold text-ink">{node.label}</span></span><span className="mt-1 block truncate text-xs text-slate-500">{node.path ?? `${node.childCount} files`}</span></button>; })}</div></section>; })}{filtered.length === 0 && <p className="text-sm text-slate-500">No components match these filters.</p>}</div></div>
      <aside className="rounded-xl border border-slate-200 p-4" aria-live="polite"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Selected component</h3>{selected ? <><p className="mt-2 break-words font-semibold text-ink">{selected.label}</p><dl className="mt-3 grid gap-2 text-xs"><div><dt className="text-slate-500">Type</dt><dd className="font-semibold text-slate-700">{selected.kind}</dd></div>{selected.path && <div><dt className="text-slate-500">Location</dt><dd className="break-all font-mono text-slate-700">{selected.path}</dd></div>}{selected.language && <div><dt className="text-slate-500">Language</dt><dd className="font-semibold text-slate-700">{selected.language}</dd></div>}<div><dt className="text-slate-500">Relationships</dt><dd className="font-semibold text-slate-700">{relationships.length}</dd></div></dl>{selected.sourceUrl && <a href={selected.sourceUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-brand-600 hover:underline">Open source <ExternalLink size={12}/></a>}<ul className="mt-4 grid gap-1 text-xs text-slate-500">{relationships.slice(0, 12).map(edge => <li key={edge.id}>{edge.label}: {graph.data!.nodes.find(node => node.id === (edge.sourceId === selected.id ? edge.targetId : edge.sourceId))?.label}</li>)}</ul></> : <p className="mt-2 text-sm text-slate-500">Select a visible node.</p>}</aside>
    </div>
  </div>;
}
