import { useMemo, useState, type Dispatch, type ReactNode, type SetStateAction } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ChevronDown, ChevronRight, ExternalLink, FileCode2, GitBranch, Layers3, LayoutGrid, Minus, Plus, RotateCcw, Route, Search, Workflow } from 'lucide-react';
import { api, getApiError } from '../api/client';

export type ArchitectureLayout = 'Architecture'|'Flowchart'|'Tree';
export interface ArchitectureNode { id: string; label: string; kind: 'Module'|'File'|'Endpoint'; path?: string; language?: string; childCount: number; sourceUrl?: string; role?: string }
export interface ArchitectureEdge { id: string; sourceId: string; targetId: string; kind: string; label: string; evidenceLevel?: 'Confirmed'|'Inferred'; sourceUrl?: string }
export interface ArchitectureGraph { schemaVersion: string; commitSha: string; isTruncated: boolean; totalNodeCount: number; nodes: ArchitectureNode[]; edges: ArchitectureEdge[] }
const icons = { Module: Layers3, File: FileCode2, Endpoint: Route };

export function filterArchitectureNodes(nodes: ArchitectureNode[], kind: string, search: string) {
  const term = search.trim().toLowerCase();
  return nodes.filter(node => (kind === 'All' || node.kind === kind) && (!term || `${node.label} ${node.path ?? ''} ${node.language ?? ''} ${node.role ?? ''}`.toLowerCase().includes(term)));
}
export function connectedNodeIds(graph: ArchitectureGraph, focusId?: string) {
  if (!focusId) return new Set(graph.nodes.map(node => node.id));
  const ids = new Set([focusId]);
  graph.edges.forEach(edge => { if (edge.sourceId === focusId) ids.add(edge.targetId); if (edge.targetId === focusId) ids.add(edge.sourceId); });
  return ids;
}

export function RepositoryArchitectureMap({ organizationId, repositoryId }: { organizationId: string; repositoryId: string }) {
  const graph = useQuery({ queryKey: ['repository-architecture', organizationId, repositoryId], queryFn: async () => (await api.get<ArchitectureGraph>(`/organizations/${organizationId}/repositories/${repositoryId}/architecture`)).data });
  const [search, setSearch] = useState(''); const [kind, setKind] = useState('All'); const [layout, setLayout] = useState<ArchitectureLayout>('Architecture');
  const [selectedId, setSelectedId] = useState<string>(); const [focusId, setFocusId] = useState<string>(); const [collapsed, setCollapsed] = useState<Set<string>>(new Set()); const [zoom, setZoom] = useState(1);
  const filtered = useMemo(() => filterArchitectureNodes(graph.data?.nodes ?? [], kind, search), [graph.data, kind, search]);
  if (graph.isLoading) return <p role="status" className="text-sm text-slate-500">Building the repository architecture map...</p>;
  if (graph.isError) return <div role="alert" className="error">Architecture map unavailable. {getApiError(graph.error)}</div>;
  if (!graph.data?.nodes.length) return <div className="rounded-xl border border-slate-200 p-6 text-center"><h3 className="font-semibold text-ink">No architecture data yet</h3><p className="mt-2 text-sm text-slate-500">Re-index this repository after adding supported source files.</p></div>;
  const data = graph.data; const visible = filtered.filter(node => connectedNodeIds(data, focusId).has(node.id));
  const selected = visible.find(node => node.id === selectedId) ?? visible[0];
  const relationships = selected ? data.edges.filter(edge => edge.sourceId === selected.id || edge.targetId === selected.id) : [];
  const toggle = (id: string) => setCollapsed(value => { const next = new Set(value); next.has(id) ? next.delete(id) : next.add(id); return next; });
  const reset = () => { setSearch(''); setKind('All'); setFocusId(undefined); setSelectedId(undefined); setCollapsed(new Set()); setZoom(1); };
  return <div>
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm text-slate-500">Commit-pinned map for {data.commitSha.slice(0, 8)}. Solid relationships are confirmed by indexed source evidence.</p>{data.isTruncated && <p className="mt-1 text-xs font-semibold text-amber-700">Showing a representative {data.nodes.length} of {data.totalNodeCount} nodes.</p>}</div><Zoom zoom={zoom} setZoom={setZoom} reset={reset}/></div>
    <div className="mt-4 flex flex-wrap gap-2" aria-label="Architecture layout">{(['Architecture','Flowchart','Tree'] as ArchitectureLayout[]).map(value => { const Icon = value === 'Architecture' ? LayoutGrid : value === 'Flowchart' ? Workflow : GitBranch; return <button key={value} type="button" aria-pressed={layout === value} onClick={() => setLayout(value)} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold ${layout === value ? 'border-brand-500 bg-brand-50 text-brand-700' : 'border-slate-200 text-slate-600'}`}><Icon size={15}/>{value}</button>; })}{focusId && <button type="button" className="ml-auto text-sm font-semibold text-brand-700 hover:underline" onClick={() => setFocusId(undefined)}>Back to full map</button>}</div>
    <div className="mt-3 grid gap-3 sm:grid-cols-[minmax(0,1fr)_12rem]"><label className="relative"><Search className="pointer-events-none absolute left-3 top-3 text-slate-400" size={16}/><span className="sr-only">Search architecture nodes</span><input className="control pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search components, roles, or files"/></label><select className="control" aria-label="Component type" value={kind} onChange={event => setKind(event.target.value)}><option>All</option><option>Module</option><option>File</option><option>Endpoint</option></select></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_20rem]">
      <div className="max-h-[42rem] overflow-auto rounded-xl border border-slate-200 bg-slate-50 p-4" aria-label={`${layout} with ${visible.length} visible nodes`}><div className="min-w-[34rem] transition-transform motion-reduce:transition-none" style={{ transform: `scale(${zoom})`, transformOrigin: 'top left' }}>{layout === 'Architecture' ? <Cards nodes={visible} selectedId={selected?.id} onSelect={setSelectedId}/> : layout === 'Flowchart' ? <Flow graph={data} nodes={visible} selectedId={selected?.id} collapsed={collapsed} onSelect={setSelectedId} onCollapse={toggle}/> : <Tree graph={data} nodes={visible} selectedId={selected?.id} collapsed={collapsed} onSelect={setSelectedId} onCollapse={toggle}/>} {!visible.length && <p className="text-sm text-slate-500">No components match these filters.</p>}</div></div>
      <Inspector graph={data} selected={selected} relationships={relationships} onFocus={setFocusId}/>
    </div><Outline graph={data}/>
  </div>;
}

function Zoom({ zoom, setZoom, reset }: { zoom: number; setZoom: Dispatch<SetStateAction<number>>; reset: () => void }) { const c = 'rounded-lg border border-slate-200 p-2 text-slate-600 hover:border-brand-300 focus:ring-2 focus:ring-brand-500'; return <div className="flex gap-1" aria-label="Map zoom controls"><button className={c} aria-label="Zoom out" onClick={() => setZoom(v => Math.max(.7,v-.1))}><Minus size={15}/></button><button className={c} aria-label="Reset map" onClick={reset}><RotateCcw size={15}/></button><button className={c} aria-label="Zoom in" onClick={() => setZoom(v => Math.min(1.4,v+.1))}><Plus size={15}/></button></div>; }
function Node({ node, selected, onSelect }: { node: ArchitectureNode; selected: boolean; onSelect: () => void }) { const Icon=icons[node.kind]; return <button type="button" aria-pressed={selected} onClick={onSelect} className={`min-w-0 w-full overflow-hidden rounded-xl border bg-white p-3 text-left focus:ring-2 focus:ring-brand-500 ${selected?'border-brand-500':'border-slate-200 hover:border-brand-300'}`}><span className="flex min-w-0 items-center gap-2"><Icon size={16} className="shrink-0 text-brand-600"/><span className="min-w-0 truncate text-sm font-semibold text-ink">{node.label}</span></span><span className="mt-1 block max-w-full truncate text-xs text-slate-500">{node.role??node.kind} · {node.path??`${node.childCount} files`}</span></button>; }
function Cards({nodes,selectedId,onSelect}:{nodes:ArchitectureNode[];selectedId?:string;onSelect:(id:string)=>void}) { return <div className="grid gap-5">{(['Module','File','Endpoint'] as const).map(kind => { const items=nodes.filter(n=>n.kind===kind); return items.length?<section key={kind}><h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{kind}s</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(n=><Node key={n.id} node={n} selected={selectedId===n.id} onSelect={()=>onSelect(n.id)}/>)}</div></section>:null; })}</div>; }
interface ViewProps { graph:ArchitectureGraph;nodes:ArchitectureNode[];selectedId?:string;collapsed:Set<string>;onSelect:(id:string)=>void;onCollapse:(id:string)=>void }
function Flow({graph,nodes,selectedId,collapsed,onSelect,onCollapse}:ViewProps) { return <div className="grid gap-5">{(['Module','File','Endpoint'] as const).map((kind,i)=>{const items=nodes.filter(n=>n.kind===kind&&!hidden(graph,n.id,collapsed));return items.length?<section key={kind} className="min-w-0 overflow-hidden"><h3 className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-500">{i?'↓ confirmed ':''}{kind}s</h3><div className="grid min-w-0 gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(n=><div key={n.id} className="grid min-w-0"><Node node={n} selected={selectedId===n.id} onSelect={()=>onSelect(n.id)}/>{graph.edges.some(e=>e.sourceId===n.id)&&<button type="button" className="mt-1 justify-self-start text-xs text-slate-500" onClick={()=>onCollapse(n.id)}>{collapsed.has(n.id)?'Expand':'Collapse'} downstream</button>}</div>)}</div></section>:null;})}</div>; }
function hidden(graph:ArchitectureGraph,id:string,collapsed:Set<string>){let todo=[id];const seen=new Set<string>();while(todo.length){const current=todo.pop()!;if(seen.has(current))continue;seen.add(current);const parents=graph.edges.filter(e=>e.targetId===current).map(e=>e.sourceId);if(parents.some(p=>collapsed.has(p)))return true;todo.push(...parents);}return false;}
function Tree({graph,nodes,selectedId,collapsed,onSelect,onCollapse}:ViewProps) { const ids=new Set(nodes.map(n=>n.id));const roots=nodes.filter(n=>!graph.edges.some(e=>e.targetId===n.id&&ids.has(e.sourceId)));const render=(n:ArchitectureNode,depth:number):ReactNode=>{const children=graph.edges.filter(e=>e.sourceId===n.id).map(e=>nodes.find(x=>x.id===e.targetId)).filter((x):x is ArchitectureNode=>!!x);return <li key={n.id} className="mt-2"><div className="flex items-center gap-2" style={{marginLeft:depth*24}}>{children.length?<button aria-label={`${collapsed.has(n.id)?'Expand':'Collapse'} ${n.label}`} onClick={()=>onCollapse(n.id)}>{collapsed.has(n.id)?<ChevronRight size={16}/>:<ChevronDown size={16}/>}</button>:<span className="w-4"/>}<div className="min-w-72 flex-1"><Node node={n} selected={selectedId===n.id} onSelect={()=>onSelect(n.id)}/></div></div>{!collapsed.has(n.id)&&<ul>{children.map(c=>render(c,depth+1))}</ul>}</li>;};return <ul aria-label="Architecture hierarchy">{roots.map(r=>render(r,0))}</ul>; }
function Inspector({graph,selected,relationships,onFocus}:{graph:ArchitectureGraph;selected?:ArchitectureNode;relationships:ArchitectureEdge[];onFocus:(id:string)=>void}) { return <aside className="rounded-xl border border-slate-200 p-4" aria-live="polite"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Selected component</h3>{selected?<><p className="mt-2 break-words font-semibold text-ink">{selected.label}</p><p className="mt-1 text-xs text-slate-500">{selected.role??selected.kind}</p>{selected.path&&<p className="mt-3 break-all font-mono text-xs">{selected.path}</p>}<div className="mt-4 flex gap-3"><button className="text-xs font-semibold text-brand-700" onClick={()=>onFocus(selected.id)}>Focus neighborhood</button>{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-semibold text-brand-700">Open source <ExternalLink size={12}/></a>}</div><ul className="mt-4 grid gap-2 text-xs text-slate-600">{relationships.slice(0,12).map(e=><li key={e.id} className={`border-l-2 pl-2 ${e.evidenceLevel==='Inferred'?'border-dashed border-amber-400':'border-brand-400'}`}><b>{e.evidenceLevel??'Confirmed'}:</b> {e.label} {graph.nodes.find(n=>n.id===(e.sourceId===selected.id?e.targetId:e.sourceId))?.label}{e.sourceUrl&&<a className="ml-1 text-brand-700" href={e.sourceUrl} target="_blank" rel="noreferrer">evidence</a>}</li>)}</ul></>:<p className="mt-2 text-sm text-slate-500">Select a visible node.</p>}</aside>; }
function Outline({graph}:{graph:ArchitectureGraph}) { return <details className="mt-4 rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold text-ink">Accessible architecture outline</summary><ol className="mt-3 grid gap-2 text-sm text-slate-600">{graph.nodes.map(n=><li key={n.id}><strong className="text-ink">{n.kind}: {n.label}</strong> ({n.role??n.kind}){graph.edges.filter(e=>e.sourceId===n.id).map(e=>` — ${e.label} ${graph.nodes.find(x=>x.id===e.targetId)?.label} (${e.evidenceLevel??'Confirmed'})`)}</li>)}</ol></details>; }
