<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\RepoNavAI.Infrastructure\RepoNavAI.Infrastructure.csproj" />
  </ItemGroup>
</Project>
