import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Copy, Pencil, Trash2, UserPlus } from 'lucide-react';
import { api, getApiError } from '../api/client';
import { useOrganization } from '../organizations/OrganizationContext';
import type { InvitationResult, OrganizationDetails, OrganizationRole, PendingInvitation } from '../organizations/types';
import { PageHeading } from './DashboardPage';

export function OrganizationSettingsPage() {
  const { current } = useOrganization(); const queryClient = useQueryClient();
  const [name, setName] = useState(current?.name ?? ''); const [error, setError] = useState(''); const [updated, setUpdated] = useState(false);
  useEffect(() => { setName(current?.name ?? ''); setError(''); setUpdated(false); }, [current?.id, current?.name]);
  const rename = useMutation({ mutationFn: () => api.patch(`/organizations/${current!.id}`, { name: name.trim() }), onSuccess: async () => { setUpdated(true); await Promise.all([queryClient.invalidateQueries({ queryKey: ['organizations'] }), queryClient.invalidateQueries({ queryKey: ['organization', current!.id] })]); }, onError: reason => { setUpdated(false); setError(getApiError(reason)); } });
  if (!current) return null;
  return <><PageHeading eyebrow="Organization administration" title="Organization settings" copy="Manage workspace-level details for this organization."/><section className="panel mt-8"><div className="panel-header"><span className="panel-icon"><Pencil size={19}/></span><div className="min-w-0"><p className="font-semibold text-ink">Organization name</p><p className="text-sm text-slate-500">Update the name shown throughout this workspace.</p></div></div><form className="mt-6 flex flex-col gap-3 sm:flex-row" onSubmit={event => { event.preventDefault(); setError(''); setUpdated(false); rename.mutate(); }}><input className="control flex-1" required maxLength={150} value={name} onChange={event => { setName(event.target.value); setUpdated(false); }} aria-label="Organization name"/><button className="button-primary" disabled={rename.isPending || !name.trim() || name.trim() === current.name}>{rename.isPending ? 'Saving…' : 'Save name'}</button></form>{error && <div className="error mt-4" role="alert">{error}</div>}{updated && <p className="alert-success mt-4" role="status">Organization name updated.</p>}</section></>;
}

export function OrganizationMembersPage() {
  const { current } = useOrganization(); const queryClient = useQueryClient();
  const [email, setEmail] = useState(''); const [inviteRole, setInviteRole] = useState<OrganizationRole>('Member'); const [inviteUrl, setInviteUrl] = useState(''); const [error, setError] = useState('');
  const canManage = current?.role === 'Owner' || current?.role === 'Administrator';
  const details = useQuery({ queryKey: ['organization', current?.id], queryFn: async () => (await api.get<OrganizationDetails>(`/organizations/${current!.id}`)).data, enabled: Boolean(current) });
  const invitations = useQuery({ queryKey: ['organization', current?.id, 'invitations'], queryFn: async () => (await api.get<PendingInvitation[]>(`/organizations/${current!.id}/invitations`)).data, enabled: Boolean(current && canManage) });
  const invite = useMutation({ mutationFn: async () => (await api.post<InvitationResult>(`/organizations/${current!.id}/invitations`, { email, role: inviteRole })).data, onSuccess: data => { setInviteUrl(`${window.location.origin}/invitations/${data.token}`); setEmail(''); queryClient.invalidateQueries({ queryKey: ['organization', current!.id, 'invitations'] }); }, onError: reason => setError(getApiError(reason)) });
  const revoke = useMutation({ mutationFn: async (invitationId: string) => api.delete(`/organizations/${current!.id}/invitations/${invitationId}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['organization', current!.id, 'invitations'] }), onError: reason => setError(getApiError(reason)) });
  const changeRole = useMutation({ mutationFn: async ({ userId, nextRole }: { userId: string; nextRole: OrganizationRole }) => api.patch(`/organizations/${current!.id}/members/${userId}`, { role: nextRole }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['organization', current!.id] }) });
  const remove = useMutation({ mutationFn: async (userId: string) => api.delete(`/organizations/${current!.id}/members/${userId}`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['organization', current!.id] }) });
  if (!current) return null;
  return <><PageHeading eyebrow="Organization administration" title="Organization members" copy="Review workspace access and manage invitations according to your role."/><section className="panel mt-8"><div className="panel-header"><span className="panel-icon"><UserPlus size={20}/></span><div className="min-w-0"><p className="font-semibold text-ink">Member directory</p><p className="text-sm text-slate-500">{canManage ? 'Manage access to this tenant workspace.' : 'People with access to this tenant workspace.'}</p></div></div>{canManage && <form className="mt-6 grid gap-3 md:grid-cols-[minmax(0,1fr)_170px_auto]" onSubmit={event => { event.preventDefault(); setError(''); setInviteUrl(''); invite.mutate(); }}><input className="control" type="email" required value={email} onChange={event => setEmail(event.target.value)} placeholder="developer@company.com" aria-label="Invitee email"/><select className="control" value={inviteRole} onChange={event => setInviteRole(event.target.value as OrganizationRole)} aria-label="Invitee role"><option value="Member">Member</option><option value="Administrator">Administrator</option></select><button className="button-primary" disabled={invite.isPending}>Invite</button></form>}{error && <div className="error mt-4" role="alert">{error}</div>}{inviteUrl && <div className="alert-success mt-4 flex items-center gap-3" role="status"><input className="min-w-0 flex-1 bg-transparent text-xs" readOnly value={inviteUrl} aria-label="Invitation link"/><button className="icon-button border-0 text-emerald-700" onClick={() => navigator.clipboard.writeText(inviteUrl)} aria-label="Copy invitation link"><Copy size={18}/></button></div>}{canManage && invitations.data && invitations.data.length > 0 && <div className="alert-warning mt-6"><p className="text-sm font-semibold">Pending invitations</p><div className="mt-2 divide-y divide-amber-200/70">{invitations.data.map(invitation => <div key={invitation.id} className="flex min-w-0 items-center gap-3 py-3"><div className="min-w-0 flex-1"><p className="break-all text-sm font-semibold text-ink">{invitation.email}</p><p className="text-xs text-slate-500">{invitation.role} · expires {new Date(invitation.expiresAtUtc).toLocaleDateString()}</p></div><button className="button-danger shrink-0 px-2" disabled={revoke.isPending} onClick={() => revoke.mutate(invitation.id)}><Trash2 size={15}/> Revoke</button></div>)}</div></div>}<MemberList details={details.data} role={current.role} canManage={canManage} onRoleChange={(userId, nextRole) => changeRole.mutate({ userId, nextRole })} onRemove={userId => remove.mutate(userId)}/></section></>;
}

function MemberList({ details, role, canManage, onRoleChange, onRemove }: { details?: OrganizationDetails; role: OrganizationRole; canManage: boolean; onRoleChange: (userId: string, role: OrganizationRole) => void; onRemove: (userId: string) => void }) {
  return <div className="mt-6 divide-y divide-slate-100">{details?.members.map(member => <div key={member.userId} className="flex min-w-0 flex-wrap items-center gap-3 py-4 sm:gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-slate-100 text-sm font-semibold text-slate-600">{member.displayName.slice(0, 1).toUpperCase()}</span><div className="min-w-0 basis-[12rem] flex-1"><p className="break-words text-sm font-semibold text-ink">{member.displayName}</p><p className="break-all text-xs text-slate-500">{member.email}</p></div>{role === 'Owner' ? <select className="control min-h-9 w-auto px-2 py-1 text-xs" value={member.role} onChange={event => onRoleChange(member.userId, event.target.value as OrganizationRole)} aria-label={`Role for ${member.displayName}`}><option value="Owner">Owner</option><option value="Administrator">Administrator</option><option value="Member">Member</option></select> : <span className="text-xs font-medium text-slate-500">{member.role}</span>}{canManage && member.role !== 'Owner' && <button className="icon-button border-0" onClick={() => onRemove(member.userId)} aria-label={`Remove ${member.displayName}`}><Trash2 size={17}/></button>}</div>)}</div>;
}
