import { useState } from 'react';
import { ArrowLeft, BookOpenCheck, Braces, CheckCircle2, ExternalLink, FileSearch, Github, LayoutDashboard, Menu, Search, Sparkles, Workflow, X } from 'lucide-react';
import { Brand } from '../components/Brand';
import { AppIcon } from '../components/AppIcon';
import { CodeFlowDiagram } from '../repositories/CodeFlowDiagram';
import { RepositoryCard } from '../repositories/RepositoryCard';
import type { CodeFlowTrace, RegisteredRepository, SemanticSearchResult } from '../repositories/types';
import { useTheme, type ThemePreference } from '../themes/ThemeContext';

const commitSha = '9480d69f27fceba448e49bb4e95745681339e261';
const repositoryUrl = 'https://github.com/jeremymwood/260805-RepoNavAI';
const sourceUrl = (path: string, line: number, endLine = line) => `${repositoryUrl}/blob/${commitSha}/${path}#L${line}-L${endLine}`;

export const demoRepositories: RegisteredRepository[] = [
  repository('reponav', 'jeremymwood', '260805-RepoNavAI', 'Completed', true, commitSha),
  repository('worker', 'acme-engineering', 'background-worker', 'Processing', false),
  repository('catalog', 'acme-engineering', 'service-catalog', 'Completed', false, '73ed11a9a900'),
  { ...repository('legacy', 'acme-engineering', 'legacy-api', 'Failed', false), errorMessage: 'Repository archive exceeded the configured fixture limit.' },
  repository('mobile', 'acme-engineering', 'mobile-client', 'Cancelled', false),
  repository('private', 'acme-engineering', 'private-platform', 'Completed', false, '8b02f3ed1000', 'Private')
];

function repository(id: string, owner: string, name: string, indexingStatus: RegisteredRepository['indexingStatus'], isFavorite: boolean, sha?: string, visibility: RegisteredRepository['visibility'] = 'Public'): RegisteredRepository {
  return { id, organizationId: 'fixture-org', owner, name, fullName: `${owner}/${name}`, defaultBranch: 'main', visibility, webUrl: id === 'reponav' ? repositoryUrl : `${repositoryUrl}#fixture-${id}`, indexingStatus, indexingCheckpoint: indexingStatus === 'Completed' ? 'Completed' : indexingStatus === 'Processing' ? 'Parsing' : indexingStatus === 'Failed' ? 'Failed' : indexingStatus === 'Cancelled' ? 'Cancelled' : 'Queued', commitSha: sha, registeredAtUtc: '2026-08-11T00:00:00Z', isFavorite };
}

export function visibleDemoRepositories(repositories: RegisteredRepository[], expanded: boolean, previewCount = 4) { return expanded ? repositories : repositories.slice(0, previewCount); }

const evidence: SemanticSearchResult[] = [
  { chunkId: 'source-1', path: 'src/RepoNavAI.Api/Controllers/RepositoriesController.cs', startLine: 103, endLine: 105, content: 'The controller sends GenerateCodeFlowTraceCommand through the application boundary.', score: .96, commitSha, sourceUrl: sourceUrl('src/RepoNavAI.Api/Controllers/RepositoriesController.cs', 103, 105) },
  { chunkId: 'source-2', path: 'src/RepoNavAI.Application/Repositories/RepositoryCodeFlowFeatures.cs', startLine: 27, endLine: 58, content: 'The handler authorizes membership, retrieves commit-pinned evidence, generates a structured draft, and validates citations.', score: .93, commitSha, sourceUrl: sourceUrl('src/RepoNavAI.Application/Repositories/RepositoryCodeFlowFeatures.cs', 27, 58) },
  { chunkId: 'source-3', path: 'src/RepoNavAI.Web/src/repositories/CodeFlowDiagram.tsx', startLine: 48, endLine: 80, content: 'The client validates the versioned trace and renders application-owned nodes, edges, citations, zoom, and text fallback.', score: .9, commitSha, sourceUrl: sourceUrl('src/RepoNavAI.Web/src/repositories/CodeFlowDiagram.tsx', 48, 80) }
];

export const demoTrace: CodeFlowTrace = {
  schemaVersion: '1.0', repositoryId: 'reponav', commitSha, summary: 'A cited code-flow request crosses the API, application retrieval, model boundary, and safe React renderer.', missingEvidence: ['Runtime model-provider scheduling is external and is not inferred from repository source.'], sources: evidence,
  steps: [
    { key: 'api', order: 1, title: 'Accept code-flow request', component: 'RepositoriesController', symbol: 'GenerateCodeFlow', responsibility: 'Accept the authorized repository question.', handoff: 'Send the application command.', boundary: 'Synchronous', evidenceLevel: 'Confirmed', citations: [citation(evidence[0]!)] },
    { key: 'retrieve', order: 2, title: 'Retrieve trusted evidence', component: 'GenerateCodeFlowTraceHandler', symbol: 'Handle', responsibility: 'Authorize the tenant and rank evidence from the latest snapshot.', handoff: 'Supply bounded evidence to the generator.', boundary: 'Asynchronous', evidenceLevel: 'Confirmed', citations: [citation(evidence[1]!)] },
    { key: 'model', order: 3, title: 'Generate structured trace', component: 'Code-flow provider', symbol: 'GenerateAsync', responsibility: 'Return versioned JSON containing cited steps and missing evidence.', handoff: 'Validate provider output.', boundary: 'External', evidenceLevel: 'Inferred', citations: [] },
    { key: 'render', order: 4, title: 'Render safe diagram', component: 'CodeFlowDiagram', symbol: 'CodeFlowDiagram', responsibility: 'Render validated application-owned graph data without executable markup.', handoff: 'Expose citations and ordered text.', boundary: 'Synchronous', evidenceLevel: 'Confirmed', citations: [citation(evidence[2]!)] }
  ]
};

function citation(source: SemanticSearchResult) { return { path: source.path, startLine: source.startLine, endLine: source.endLine, commitSha: source.commitSha, sourceUrl: source.sourceUrl }; }

type DemoView = 'summary' | 'search' | 'endpoints' | 'assistant' | 'flow';

export function DemoPage() {
  const [repositories, setRepositories] = useState(demoRepositories); const [expanded, setExpanded] = useState(false); const [selectedId, setSelectedId] = useState<string>();
  const [view, setView] = useState<DemoView>('summary'); const [mobileOpen, setMobileOpen] = useState(false); const { preference, setPreference } = useTheme();
  const selected = repositories.find(item => item.id === selectedId);
  function updateRepository(id: string, update: (current: RegisteredRepository) => RegisteredRepository) { setRepositories(items => items.map(item => item.id === id ? update(item) : item)); }

  return <div className="min-h-screen bg-canvas text-ink">
    <header className="sticky top-0 z-30 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="flex h-16 min-w-0 items-center gap-2 px-3 sm:gap-3 sm:px-6"><button type="button" className="icon-button md:hidden" aria-label={mobileOpen ? 'Close preview navigation' : 'Open preview navigation'} aria-expanded={mobileOpen} onClick={() => setMobileOpen(value => !value)}><AppIcon icon={mobileOpen ? X : Menu}/></button><Brand/><span className="ml-auto hidden rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800 lg:inline-flex">Read-only fixture demo</span><label className="ml-auto hidden items-center gap-2 text-xs font-semibold text-slate-500 sm:flex lg:ml-0">Theme<select aria-label="Preview theme" className="h-9 rounded-lg border border-slate-200 bg-white px-2 text-ink" value={preference} onChange={event => setPreference(event.target.value as ThemePreference)}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><a className="icon-button ml-auto sm:ml-0" aria-label="View source on GitHub" href={repositoryUrl} target="_blank" rel="noreferrer"><AppIcon icon={Github}/></a></div></header>
    <div className="flex min-h-[calc(100vh-4rem)]">
      <aside className={`${mobileOpen ? 'fixed inset-x-0 top-16 z-20 flex' : 'hidden'} w-full flex-col border-r border-slate-200 bg-white p-4 md:static md:flex md:w-60`}><p className="px-3 text-xs font-bold uppercase tracking-[.16em] text-slate-500">Public preview</p><button className="mt-3 flex items-center gap-3 rounded-xl bg-brand-50 px-3 py-3 text-left text-sm font-semibold text-brand-700" onClick={() => { setSelectedId(undefined); setMobileOpen(false); }}><AppIcon icon={LayoutDashboard}/> Overview</button><a href="#repositories" className="mt-1 flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-50" onClick={() => setMobileOpen(false)}><AppIcon icon={Github}/> Repositories</a><div className="mt-auto rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">All content is bundled fixture data. No API, authentication, ingestion, or AI provider is contacted.</div></aside>
      <main className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8">{selected ? <RepositoryDemo repository={selected} view={view} onView={setView} onBack={() => { setSelectedId(undefined); setView('summary'); }}/> : <Overview repositories={repositories} expanded={expanded} onExpanded={setExpanded} onExplore={id => { setSelectedId(id); setView('summary'); }} onFavorite={id => updateRepository(id, item => ({ ...item, isFavorite: !item.isFavorite }))} onCancel={id => updateRepository(id, item => ({ ...item, indexingStatus: 'Cancelled', indexingCheckpoint: 'Cancelled' }))} onRetry={id => updateRepository(id, item => ({ ...item, indexingStatus: 'Processing', indexingCheckpoint: 'Parsing', errorMessage: undefined }))}/>}</main>
    </div>
  </div>;
}

function Overview({ repositories, expanded, onExpanded, onExplore, onFavorite, onCancel, onRetry }: { repositories: RegisteredRepository[]; expanded: boolean; onExpanded: (value: boolean) => void; onExplore: (id: string) => void; onFavorite: (id: string) => void; onCancel: (id: string) => void; onRetry: (id: string) => void }) {
  const visible = visibleDemoRepositories(repositories, expanded);
  return <><section className="rounded-2xl bg-hero p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-200">Acme Engineering</p><h1 className="mt-3 text-3xl font-semibold">Understand unfamiliar systems with cited evidence.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Explore a static walkthrough of RepoNavAI’s current repository workflow, analysis tools, and safe code-flow visualization.</p></section><section id="repositories" className="mt-8 scroll-mt-24 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="eyebrow">Fixture repositories</p><h2 className="mt-2 text-2xl font-semibold">Repository overview</h2><p className="mt-1 text-sm text-slate-500">Favorite, cancel, and retry controls update local fixture state only.</p></div><span className="inline-flex items-center gap-2 text-xs font-semibold text-emerald-700"><CheckCircle2 size={16}/> No network actions</span></div><div className="mt-6 grid gap-3 lg:grid-cols-2">{visible.map(repository => <RepositoryCard key={repository.id} repository={repository} selected={false} onFavorite={() => onFavorite(repository.id)} onCancel={() => onCancel(repository.id)} onRetry={() => onRetry(repository.id)} onExplore={() => onExplore(repository.id)}/>)}</div>{repositories.length > 4 && <button type="button" className="mx-auto mt-5 block rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-brand-600" aria-expanded={expanded} onClick={() => onExpanded(!expanded)}>{expanded ? 'Show less' : `Show more (${repositories.length - visible.length} hidden)`}</button>}</section></>;
}

function RepositoryDemo({ repository, view, onView, onBack }: { repository: RegisteredRepository; view: DemoView; onView: (view: DemoView) => void; onBack: () => void }) {
  const tools: Array<[DemoView, string, typeof Search]> = [['summary', 'Analysis summary', BookOpenCheck], ['search', 'Source search', Search], ['endpoints', 'API endpoints', Braces], ['assistant', 'Cited answer', Sparkles], ['flow', 'Code flow', Workflow]];
  return <><button type="button" className="inline-flex items-center gap-2 text-sm font-semibold text-brand-600" onClick={onBack}><ArrowLeft size={16}/> Back to repositories</button><header className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><p className="text-xs font-semibold text-slate-500">{repository.owner}/</p><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="mt-1 break-all text-2xl font-semibold">{repository.name}</h1><a href={repository.webUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-brand-600">Open fixture source <ExternalLink size={12}/></a></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Completed</span></div><div className="mt-4 flex flex-wrap gap-4 border-t border-slate-100 pt-4 text-xs text-slate-500"><span>Public</span><span>Branch: <strong>main</strong></span><span>Commit: <strong>{repository.commitSha?.slice(0,8)}</strong></span><span>5 analysis capabilities</span></div></header><nav aria-label="Fixture repository tools" className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{tools.map(([key, label, Icon]) => <button key={key} type="button" aria-current={view === key ? 'page' : undefined} className={`flex items-center gap-2 rounded-xl border p-3 text-left text-sm font-semibold ${view === key ? 'border-brand-500 bg-brand-50 text-brand-700' : 'border-slate-200 bg-white text-slate-600'}`} onClick={() => onView(key)}><AppIcon icon={Icon}/>{label}</button>)}</nav><section className="mt-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">{view === 'summary' && <Summary/>}{view === 'search' && <Evidence/>}{view === 'endpoints' && <Endpoints/>}{view === 'assistant' && <Answer/>}{view === 'flow' && <FlowTrace/>}</section></>;
}

function Summary() { return <div><h2 className="font-semibold">Analysis coverage</h2><p className="mt-1 text-sm text-slate-500">This fixture represents the latest completed index at commit {commitSha.slice(0,8)}.</p><div className="mt-4 flex flex-wrap gap-2">{['Indexed source','C# source','Documentation','Tests','API endpoints'].map(item => <span key={item} className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">{item}: Available</span>)}</div></div>; }
function Evidence() { return <div><div className="flex items-center gap-2"><FileSearch size={18} className="text-brand-600"/><h2 className="font-semibold">Source matches</h2></div><div className="mt-4 grid gap-3">{evidence.map(source => <article key={source.chunkId} className="rounded-xl border border-slate-200 p-4"><a href={source.sourceUrl} target="_blank" rel="noreferrer" className="break-all text-sm font-semibold text-brand-600">{source.path}:{source.startLine}-{source.endLine}</a><pre className="mt-3 max-h-40 overflow-auto whitespace-pre-wrap text-xs leading-5 text-slate-600">{source.content}</pre></article>)}</div></div>; }
function Endpoints() { const [expanded, setExpanded] = useState(false); const rows = [['POST','/repositories/{id}/code-flow','RepositoriesController.GenerateCodeFlow'],['GET','/repositories/{id}/semantic-search','RepositoriesController.SemanticSearch'],['POST','/repositories/{id}/chat','RepositoriesController.Chat'],['GET','/repositories/{id}/capabilities','RepositoriesController.GetCapabilities'],['POST','/repositories/{id}/indexing/reindex','RepositoriesController.Reindex'],['PUT','/repositories/{id}/favorite','RepositoriesController.SetFavorite']]; const visible = expanded ? rows : rows.slice(0,4); return <div><h2 className="font-semibold">API endpoints</h2><p className="mt-1 text-sm text-slate-500">Showing {visible.length} of {rows.length} fixture routes.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="text-xs uppercase text-slate-400"><tr><th className="pb-3">Method</th><th>Route</th><th>Handler</th></tr></thead><tbody>{visible.map(row => <tr key={row[1]} className="border-t border-slate-100"><td className="py-3 font-bold text-brand-700">{row[0]}</td><td className="font-mono text-xs">{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table></div><button type="button" className="mt-4 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-brand-600" aria-expanded={expanded} onClick={() => setExpanded(value => !value)}>{expanded ? 'Show less' : `Show all ${rows.length} endpoints`}</button></div>; }
function Answer() { return <div><div className="flex items-center gap-2"><Sparkles size={18} className="text-brand-600"/><h2 className="font-semibold">Cited repository answer</h2></div><div className="mt-4 rounded-xl bg-slate-50 p-4"><p className="text-sm leading-6 text-slate-700">The request is authorized at the repository boundary, grounded against the latest completed snapshot, and returned as validated structured data. Material claims remain linked to immutable source evidence.</p></div><div className="mt-3 flex flex-wrap gap-2">{evidence.slice(0,2).map((source,index) => <a key={source.chunkId} href={source.sourceUrl} target="_blank" rel="noreferrer" className="rounded bg-brand-50 px-2 py-1 text-xs text-brand-700">[{index + 1}] {source.path}:{source.startLine}-{source.endLine}</a>)}</div><p className="mt-4 text-xs text-slate-500">Fixture response only. Asking a new question does not contact an AI provider.</p></div>; }
function FlowTrace() { return <div><div className="flex items-center gap-2"><Workflow size={18} className="text-brand-600"/><h2 className="font-semibold">Interactive cited code flow</h2></div><p className="mt-2 text-sm leading-6 text-slate-600">{demoTrace.summary}</p><CodeFlowDiagram trace={demoTrace}/><details className="mt-4 rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer text-sm font-semibold">Underlying retrieved evidence ({evidence.length})</summary><div className="mt-3 grid gap-2">{evidence.map(source => <a key={source.chunkId} href={source.sourceUrl} target="_blank" rel="noreferrer" className="break-all rounded-lg bg-slate-50 p-3 text-xs font-semibold text-brand-700">{source.path}:{source.startLine}-{source.endLine}</a>)}</div></details></div>; }
