name: Deploy staging

on:
  workflow_run:
    workflows: [Publish containers]
    types: [completed]

permissions:
  actions: read
  contents: read
  id-token: write
  packages: read

jobs:
  staging:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/_deploy-azure.yml
    with:
      environment: staging
      publish-run-id: ${{ github.event.workflow_run.id }}
    secrets: inherit
